server:
  port: 5000
shiro:
  # ???? (???????????????MESSAGE_BLOCK??????????)
  # ????????????
  plugin-list:
    - com.aliceandtheworld.alicesworld.plugin.LogPlugin #???????
    - com.aliceandtheworld.alicesworld.plugin.GangBanPlugin